// This file is auto-generated by openapi-typescript
// Run `npm run generate:api` to regenerate

// Placeholder types until OpenAPI spec is available
export interface paths {}

export interface components {
  schemas: {};
  responses: {};
  parameters: {};
  requestBodies: {};
  headers: {};
  pathItems: {};
}

export interface operations {}
